---

- hosts: all
  pre_tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Ensure depdencies are installed
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - apt-transport-https
        - ca-certificates

    - name: Prevent daemons from starting after installing a package
      copy:
        dest: /usr/sbin/policy-rc.d
        mode: '0755'
        content: "#!/bin/sh\nexit 101\n"

    - name: Install build dependencies
      package:
        name: "{{ item }}"
      with_items:
        - libcurl4-openssl-dev
        - libssl-dev
        - libgmp3-dev
