- hosts: all
  roles:
    - role: geerlingguy.nginx
      nginx_remove_default_vhost: true
      nginx_server_tokens: 'off'
      nginx_worker_processes: auto
  tasks:
    - name: render /etc/nginx/conf.d/RStudioAMI.conf
      notify: reload nginx
      copy:
        dest: /etc/nginx/conf.d/RStudioAMI.conf
        mode: '0644'
        content: |
          map $http_upgrade $connection_upgrade {
            default upgrade;
            ''      close;
          }

          server {
            listen 80 default_server;
            location / {
              proxy_pass http://localhost:8787;
              proxy_redirect http://localhost:8787/ $scheme://$host/;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection $connection_upgrade;
              proxy_read_timeout 20d;
              access_log /var/log/nginx/rstudio-access.log;
              error_log  /var/log/nginx/rstudio-error.log;
            }
          }
